require("modules.plugin_config.lualine")
require("modules.plugin_config.treesitter")
require("modules.plugin_config.telescope")
require("modules.plugin_config.completions")
require("modules.plugin_config.lsp_config")
require("modules.plugin_config.nvim-tree")
require("modules.plugin_config.colorizer")
require("modules.plugin_config.gitsigns")
require("modules.plugin_config.lsp_saga")
require("modules.plugin_config.autopairs")
require("modules.plugin_config.wilder")
require("modules.plugin_config.tabby")

-- Themes
require("modules.plugin_config.themes.catppuccin")
